name: Provisioning with Terraform after signing in to AWS
on: [push]

permissions:
      id-token: write
      contents: read

jobs:
  network:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Network/Terraform Init
        id: network-init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
        run: terraform init
        working-directory: ./network/primary

      - name: Network/Terraform Plan
        id: network-plan
        run: terraform apply -auto-approve -lock=false
        working-directory: ./network/primary

      - name: Terraform Init
        id: init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
        run: terraform init
        working-directory: ./database/mysql

      - name: Terraform Plan
        run: terraform apply -lock=false
        working-directory: ./database/mysql
